/**
 * Pure classification for the isolated OLX browser probe.
 * Kept separate from the production OlxSource HTTP adapter.
 */

export {
  OLX_BROWSER_APARTMENTS_URL,
  OLX_BROWSER_HOUSES_URL,
  buildOlxBrowserCategoryUrl,
} from "../sources/olx/olx-browser.coverage.ts";

export type OlxBrowserOutcome =
  | "browser_accessible"
  | "challenge_detected"
  | "parser_failure"
  | "transport_blocked";

export type OlxBrowserProbeSignals = {
  requestedUrl: string;
  finalUrl: string;
  title: string;
  bodyText: string;
  httpStatus?: number;
  contentType?: string;
};

export type OlxBrowserClassification = {
  outcome: OlxBrowserOutcome;
  success: boolean;
  challengeIndicators: string[];
  listingSignals: string[];
  notes: string[];
};

const CHALLENGE_PATTERNS: Array<{ id: string; re: RegExp }> = [
  { id: "title_just_a_moment", re: /just a moment/i },
  { id: "title_attention_required", re: /attention required/i },
  { id: "cf_challenge_platform", re: /cf-challenge|challenge-platform|cdn-cgi\/challenge/i },
  { id: "cf_browser_verification", re: /cf-browser-verification|cf_chl_/i },
  { id: "captcha_widget", re: /g-recaptcha|hcaptcha|captcha-delivery/i },
  { id: "datadome", re: /datadome|dd_?captcha/i },
  { id: "access_challenge_copy", re: /verify you are human|checking your browser/i },
];

const BLOCKED_PATTERNS: Array<{ id: string; re: RegExp }> = [
  { id: "cloudfront_access_denied", re: /<title>\s*ERROR: The request could not be satisfied\s*<\/title>/i },
  { id: "cloudfront_403_copy", re: /Request blocked|Generated by cloudfront|The Amazon CloudFront distribution/i },
  { id: "access_denied_title", re: /access denied|403 forbidden/i },
];

/** Signals that a normal OLX catalog (not a challenge shell) exposed listing structure. */
const LISTING_PATTERNS: Array<{ id: string; re: RegExp }> = [
  { id: "data_cy_l_card", re: /data-cy=["']l-card["']/i },
  { id: "data_testid_listing", re: /data-testid=["'][^"']*listing[^"']*["']/i },
  { id: "offer_id_html_link", re: /\/d\/[^"'?\s]*ID[A-Za-z0-9]+\.html/i },
  { id: "listing_grid", re: /listing-grid|css-1sw7q4x|offersList/i },
  { id: "next_data_offers", re: /__NEXT_DATA__[\s\S]{0,8000}?"offers"/i },
  { id: "total_elements_json", re: /"total_elements"\s*:\s*[1-9]/ },
];

export function detectChallengeIndicators(title: string, bodyText: string): string[] {
  const hay = `${title}\n${bodyText}`;
  return CHALLENGE_PATTERNS.filter((p) => p.re.test(hay)).map((p) => p.id);
}

export function detectBlockedIndicators(title: string, bodyText: string): string[] {
  const hay = `${title}\n${bodyText}`;
  return BLOCKED_PATTERNS.filter((p) => p.re.test(hay)).map((p) => p.id);
}

export function detectListingSignals(bodyText: string): string[] {
  return LISTING_PATTERNS.filter((p) => p.re.test(bodyText)).map((p) => p.id);
}

/**
 * Classify one browser navigation result.
 * Order: transport_blocked → challenge_detected → browser_accessible → parser_failure.
 * HTML 200 alone is never success.
 */
export function classifyOlxBrowserProbe(input: OlxBrowserProbeSignals): OlxBrowserClassification {
  const title = input.title ?? "";
  const bodyText = input.bodyText ?? "";
  const challengeIndicators = detectChallengeIndicators(title, bodyText);
  const blockedIndicators = detectBlockedIndicators(title, bodyText);
  const listingSignals = detectListingSignals(bodyText);
  const notes: string[] = [];
  const status = input.httpStatus;

  if (status === 403 || status === 429) {
    notes.push(`HTTP ${status} on document response`);
    return {
      outcome: "transport_blocked",
      success: false,
      challengeIndicators,
      listingSignals,
      notes: [...notes, ...blockedIndicators.map((id) => `blocked:${id}`)],
    };
  }

  if (blockedIndicators.length > 0 && listingSignals.length === 0) {
    notes.push("blocked page indicators without listing payload");
    return {
      outcome: "transport_blocked",
      success: false,
      challengeIndicators,
      listingSignals,
      notes: [...notes, ...blockedIndicators.map((id) => `blocked:${id}`)],
    };
  }

  if (challengeIndicators.length > 0 && listingSignals.length === 0) {
    notes.push("bot/challenge interstitial indicators present");
    return {
      outcome: "challenge_detected",
      success: false,
      challengeIndicators,
      listingSignals,
      notes,
    };
  }

  if (listingSignals.length > 0 && (status === undefined || status < 400)) {
    notes.push("supported listing structure signals present in page HTML");
    return {
      outcome: "browser_accessible",
      success: true,
      challengeIndicators,
      listingSignals,
      notes,
    };
  }

  notes.push("page reached without supported listing payload; HTML status alone is not PASS");
  return {
    outcome: "parser_failure",
    success: false,
    challengeIndicators,
    listingSignals,
    notes,
  };
}
