import { describe, expect, it } from "vitest";
import {
  classifyOlxBrowserProbe,
  detectChallengeIndicators,
  detectListingSignals,
  OLX_BROWSER_APARTMENTS_URL,
  OLX_BROWSER_HOUSES_URL,
} from "../src/probe/olx-browser-classify.ts";

describe("OLX browser probe classification", () => {
  it("marks transport_blocked on HTTP 403 CloudFront HTML", () => {
    const classified = classifyOlxBrowserProbe({
      requestedUrl: OLX_BROWSER_APARTMENTS_URL,
      finalUrl: OLX_BROWSER_APARTMENTS_URL,
      httpStatus: 403,
      contentType: "text/html",
      title: "ERROR: The request could not be satisfied",
      bodyText: "<html>Generated by cloudfront Access Denied</html>",
    });
    expect(classified.outcome).toBe("transport_blocked");
    expect(classified.success).toBe(false);
  });

  it("marks challenge_detected when interstitial markers appear without listings", () => {
    const body = '<div id="challenge-platform" class="cf-browser-verification">Just a moment...</div>';
    expect(detectChallengeIndicators("Just a moment...", body).length).toBeGreaterThan(0);
    const classified = classifyOlxBrowserProbe({
      requestedUrl: OLX_BROWSER_HOUSES_URL,
      finalUrl: OLX_BROWSER_HOUSES_URL,
      httpStatus: 200,
      contentType: "text/html",
      title: "Just a moment...",
      bodyText: body,
    });
    expect(classified.outcome).toBe("challenge_detected");
    expect(classified.success).toBe(false);
  });

  it("marks browser_accessible when supported listing signals are present", () => {
    const body = `
      <div data-cy="l-card"><a href="/d/uk/obyavlenie/kvartyra-ID11gWHG.html">x</a></div>
      <script>window.__NEXT_DATA__ = ${JSON.stringify({ props: { pageProps: { offers: [{ id: 1 }] } } })}</script>
    `;
    expect(detectListingSignals(body)).toEqual(
      expect.arrayContaining(["data_cy_l_card", "offer_id_html_link"]),
    );
    const classified = classifyOlxBrowserProbe({
      requestedUrl: OLX_BROWSER_APARTMENTS_URL,
      finalUrl: OLX_BROWSER_APARTMENTS_URL,
      httpStatus: 200,
      contentType: "text/html; charset=utf-8",
      title: "Оренда квартир Львів",
      bodyText: body,
    });
    expect(classified.outcome).toBe("browser_accessible");
    expect(classified.success).toBe(true);
  });

  it("marks parser_failure for HTML 200 without listing payload (not PASS)", () => {
    const classified = classifyOlxBrowserProbe({
      requestedUrl: OLX_BROWSER_HOUSES_URL,
      finalUrl: OLX_BROWSER_HOUSES_URL,
      httpStatus: 200,
      contentType: "text/html",
      title: "OLX",
      bodyText: "<html><body><main>Empty shell without cards</main></body></html>",
    });
    expect(classified.outcome).toBe("parser_failure");
    expect(classified.success).toBe(false);
  });

  it("does not treat bare HTTP 200 as browser_accessible", () => {
    const classified = classifyOlxBrowserProbe({
      requestedUrl: OLX_BROWSER_APARTMENTS_URL,
      finalUrl: OLX_BROWSER_APARTMENTS_URL,
      httpStatus: 200,
      title: "ok",
      bodyText: "<html></html>",
    });
    expect(classified.outcome).not.toBe("browser_accessible");
    expect(classified.success).toBe(false);
  });
});
